### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/signals#5]
- [x] Decide on a name
- [x] Do a test run with porting devtools' state management over
- [x] Add Preact bindings
- [x] Port devtools to Preact bindings
- [x] Announcement post
- [x] docs

**Comment by marvinhagemeister** [comment]
We're live 🎉
